/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DataAuditRouteImport } from './routes/data-audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRefreshDataRouteImport } from './routes/api/public/hooks/refresh-data'

const DataAuditRoute = DataAuditRouteImport.update({
  id: '/data-audit',
  path: '/data-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshDataRoute =
  ApiPublicHooksRefreshDataRouteImport.update({
    id: '/api/public/hooks/refresh-data',
    path: '/api/public/hooks/refresh-data',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-audit': typeof DataAuditRoute
  '/api/public/hooks/refresh-data': typeof ApiPublicHooksRefreshDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-audit': typeof DataAuditRoute
  '/api/public/hooks/refresh-data': typeof ApiPublicHooksRefreshDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-audit': typeof DataAuditRoute
  '/api/public/hooks/refresh-data': typeof ApiPublicHooksRefreshDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-audit' | '/api/public/hooks/refresh-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-audit' | '/api/public/hooks/refresh-data'
  id: '__root__' | '/' | '/data-audit' | '/api/public/hooks/refresh-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataAuditRoute: typeof DataAuditRoute
  ApiPublicHooksRefreshDataRoute: typeof ApiPublicHooksRefreshDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/data-audit': {
      id: '/data-audit'
      path: '/data-audit'
      fullPath: '/data-audit'
      preLoaderRoute: typeof DataAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-data': {
      id: '/api/public/hooks/refresh-data'
      path: '/api/public/hooks/refresh-data'
      fullPath: '/api/public/hooks/refresh-data'
      preLoaderRoute: typeof ApiPublicHooksRefreshDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataAuditRoute: DataAuditRoute,
  ApiPublicHooksRefreshDataRoute: ApiPublicHooksRefreshDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
